version: "3"

services:
  # NGINX
  nginx:
    image: hagen013/psy_nginx:latest
    restart: unless-stopped
    hostname: nginx
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/psy:/media
    links:
      - web:web
    depends_on:
      - web
  # WEB
  web:
    image: hagen013/psy_server:latest
    restart: unless-stopped
    hostname: web
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    env_file:
      - env/web
    volumes:
      - /var/psy:/var/psy
    links:
      - postgres:postgres
    depends_on:
      - postgres
  # POSTGRES
  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - /var/postgres_psy/data:/var/postgres_psy/data
    env_file:
      - env/postgres